[project]
name = "api-bot"
type = "python"

[phases.setup]
commands = [
    # Atualizar pacotes e instalar dependências do Chrome e Xvfb
    "apt-get update && apt-get install -y wget gnupg2 unzip xvfb curl",

    # Adicionar repositório do Google Chrome
    "wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -",
    "sh -c 'echo \"deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main\" >> /etc/apt/sources.list.d/google-chrome.list'",

    # Instalar Google Chrome
    "apt-get update && apt-get install -y google-chrome-stable"
]

[phases.install]
commands = [
    # Instalar dependências Python do requirements.txt
    "python3 -m pip install --upgrade pip",
    "python3 -m pip install -r requirements.txt"
]

[phases.build]
commands = [
    "google-chrome --version",
    "python3 --version"
]

[phases.start]
commands = [
    # Rodar seu script headless com xvfb
    "xvfb-run -a python3 cloudflare_undetected.py"
]
