[project]
name = "api-bot"
type = "python"

[phases.setup]
commands = [
    # Atualizar pacotes e instalar dependências do Chrome
    "apt-get update && apt-get install -y wget gnupg2 unzip xvfb curl",
    
    # Adicionar repositório do Google Chrome
    "wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -",
    "sh -c 'echo \"deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main\" >> /etc/apt/sources.list.d/google-chrome.list'",
    
    # Instalar Google Chrome estável
    "apt-get update && apt-get install -y google-chrome-stable",

    # Instalar pip se não tiver
    "python3 -m ensurepip --upgrade"
]

[phases.install]
commands = [
    # Criar virtualenv e instalar dependências do Python
    "python3 -m venv /opt/venv --copies",
    ". /opt/venv/bin/activate && pip install --upgrade pip",
    ". /opt/venv/bin/activate && pip install -r requirements.txt"
]

[phases.build]
commands = [
    # Opcional: testar se Chrome e Python funcionam
    "google-chrome --version",
    "python3 --version"
]

[phases.start]
command = ". /opt/venv/bin/activate && xvfb-run -a python cloudflare_undetected.py"
